ARCH = ia32
#ARCH = 'amd64'

ifeq "$(ARCH)" "ia32"
	SIZE_VOID = 4
else
	SIZE_VOID = 8
endif

CPPFLAGS += -Wall

ifndef COMSPEC
    CPPFLAGS += -I/opt/cprocsp/include
    CPPFLAGS += -I/opt/cprocsp/include/cpcsp
    CPPFLAGS += -I/opt/cprocsp/include/asn1c/rtsrc
    CPPFLAGS += -I/opt/cprocsp/include/asn1data
    CPPFLAGS += -DUNIX
    CPPFLAGS += -DHAVE_LIMITS_H
    CPPFLAGS += -DHAVE_STDINT_H
    CPPFLAGS += -DSIZEOF_VOID_P=$(SIZE_VOID)
    CPPFLAGS += -DCP_IOVEC_USE_SYSTEM

    LDLIBS += -lpthread
    LDLIBS += -lasn1data
    LDLIBS += -lssp
    LDLIBS += -lcapi20

    LDFLAGS += -L/opt/cprocsp/lib/$(ARCH)

    EXE = 
else
    EXE = .exe
endif

